### ISSUE TITLE
[Feature] hugegraph-ai roadmap

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph-ai#2]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

If you are interested in the following tasks, feel free to claim them. Just comment below with the feature you would like to implement and create the corresponding issue.

- **hugegraph-llm**
  - [ ] Knowledge graph construction by llm
  - [ ] Use natural language to operate graph databases （gremlin）
  - [ ] Knowledge graph supplements answer context
- **hugegraph-ml**
  - [ ] integration of HugeGraph with networkx
  - [ ] ....
- **hugegraph-python-client**
  - [ ] add mutil hugegraph version unit test
  - [ ] add unit test and document for graph api
  - [ ] add unit test and document for graphs api
  - [ ] add unit test and document for schema api
  - [ ] add unit test and document for gremlin api
  - [ ] implement auth api, add unit test and document
  - [ ] implement job api, add unit test and document
  - [ ] implement metrics api, add unit test and document
  - [ ] implement task api, add unit test and document
  - [ ] implement traverser api, add unit test and document
  - [ ] implement variables api, add unit test and document
  - [ ] implement version api, add unit test and document
- **others**
  - [ ] introduce python code formatter tool（black/...）
  - [ ] add hugegraph-ai ci
  - [ ] improve unit test coverage
  - [ ] improve documents

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lzyxx77** [comment]
I would like to implement the feature Knowledge graph construction by llm， thank you！

**Comment by haohao0103** [comment]
@simon824 hi,  I can try to implement [Feature] Convert natural language to gremlin #10;thanks

**Comment by simon824** [comment]
> @simon824 hi, I can try to implement [Feature] Convert natural language to gremlin #10;thanks

Welcome to contribute!!  you can implement it after this initial pull request (https://github.com/apache/incubator-hugegraph-ai/pull/7) to be merged, and you can reuse some of its methods.

**Comment by frankjiang777** [comment]
I want to try python code review & test .

**Comment by simon824** [comment]
> I want to try python code review & test .

Hi @frankjiang777 , can u try to implement #14 ? if you need help, just contact me.

**Comment by lzyxx77** [comment]
hi, @simon824 ,I want to try extract schema from HugeGraph for kg construction!

**Comment by liuxiaocs7** [comment]
Hi, @simon, after #28 and #29, here can be updated

**Comment by simon824** [comment]
> @simon824 hi, I can try to implement [Feature] Convert natural language to gremlin #10;thanks

Hi @haohao0103 , is it still in progress?
